import type { ContentItem } from "./types"

export const content: ContentItem[] = [
    // ── Articles ──────────────────────────────────────────────
    {
        slug: "learning-by-breaking-things",
        title: "Learning by Breaking Things on Purpose",
        excerpt:
            "Sometimes the fastest way to understand how something works is to take it apart, push it too far, or let it fall apart in your hands.",
        date: "2025-11-20",
        displayDate: "November 20, 2025",
        readingTime: "3 min",
        image: "/images/blog/learning-by-breaking.png",
        medium: "article",
        memberOnly: true,
        categories: ["devops"],
        tags: ["kubernetes", "docker"],
    },
    {
        slug: "terraform-patterns-for-multi-cloud",
        title: "Terraform Patterns for Multi-Cloud Deployments",
        excerpt:
            "Practical module patterns that keep your Terraform DRY across AWS, GCP, and Azure without sacrificing clarity.",
        date: "2025-11-05",
        displayDate: "November 05, 2025",
        readingTime: "7 min",
        image: "/images/blog/terraform-patterns.png",
        medium: "article",
        categories: ["cloud", "devops"],
        tags: ["terraform", "aws"],
    },
    {
        slug: "why-i-moved-to-astro",
        title: "Why I Moved My Site to Astro",
        excerpt:
            "After years on Next.js, Astro's island architecture finally gave me the performance and simplicity I wanted for a content site.",
        date: "2025-10-18",
        displayDate: "October 18, 2025",
        readingTime: "5 min",
        image: "/images/blog/why-i-moved-to-astro.png",
        medium: "article",
        categories: ["frontend"],
        tags: ["react", "typescript"],
    },
    {
        slug: "ci-cd-for-small-teams",
        title: "CI/CD Pipelines for Small Teams",
        excerpt:
            "You don't need a platform team to ship reliably. Here's a lightweight pipeline setup that punches above its weight.",
        date: "2025-09-22",
        displayDate: "September 22, 2025",
        readingTime: "6 min",
        image: "/images/blog/ci-cd-small-teams.png",
        medium: "article",
        categories: ["devops"],
        tags: ["ci-cd", "docker"],
    },
    {
        slug: "go-error-handling-patterns",
        title: "Go Error Handling Patterns That Actually Scale",
        excerpt:
            "Moving beyond if err != nil with structured errors, sentinel values, and the errors.As/Is pattern.",
        date: "2025-08-30",
        displayDate: "August 30, 2025",
        readingTime: "8 min",
        image: "/images/blog/go-error-handling.png",
        medium: "article",
        categories: ["backend"],
        tags: ["go"],
    },

    // ── Podcasts ──────────────────────────────────────────────
    {
        slug: "why-clean-code-still-matters-most",
        title: "Why Clean Code Still Matters Most",
        excerpt:
            "Clean code isn't outdated\u2014it's what keeps teams moving forward.",
        date: "2025-11-10",
        displayDate: "November 10, 2025",
        image: "/images/podcasts/why-clean-code-still-matters-most.png",
        medium: "podcast",
        duration: "42 min",
        categories: ["leadership"],
        tags: ["typescript"],
    },
    {
        slug: "building-smarter-tools-for-daily-workflows",
        title: "Building Smarter Tools for Daily Workflows",
        excerpt:
            "Small tools can drastically improve how we work every day.",
        date: "2025-11-05",
        displayDate: "November 05, 2025",
        image: "/images/podcasts/building-smarter-tools-for-daily-workflows.png",
        medium: "podcast",
        duration: "38 min",
        categories: ["devops"],
        tags: ["nodejs"],
    },
    {
        slug: "what-makes-a-framework-truly-powerful",
        title: "What Makes a Framework Truly Powerful",
        excerpt:
            "A powerful framework changes how you think, not just what you build.",
        date: "2025-10-30",
        displayDate: "October 30, 2025",
        image: "/images/podcasts/what-makes-a-framework-truly-powerful.png",
        medium: "podcast",
        duration: "35 min",
        categories: ["frontend"],
        tags: ["react"],
    },
    {
        slug: "homesteading-and-software-parallels",
        title: "Homesteading and Software: Surprising Parallels",
        excerpt:
            "What growing your own food teaches you about building resilient systems.",
        date: "2025-10-15",
        displayDate: "October 15, 2025",
        image: "/images/podcasts/homesteading-parallels.png",
        medium: "podcast",
        duration: "45 min",
        categories: ["homesteading"],
        tags: ["gardening"],
    },

    // ── Readings ──────────────────────────────────────────────
    {
        slug: "bloom-where-the-sparks-fall",
        title: "Bloom Where the Sparks Fall",
        author: "Nira Callaway",
        excerpt:
            "A vivid, high-energy novel about fleeting brilliance, emotional aftershocks, and the courage to rebuild in the glow of what's been shattered.",
        date: "2025-11-11",
        displayDate: "November 11, 2025",
        image: "/images/readings/bloom-where-the-sparks-fall.png",
        medium: "reading",
        categories: ["faith"],
        tags: ["community"],
    },
    {
        slug: "the-starglass-constellation",
        title: "The Starglass Constellation",
        author: "Elira Thornveil",
        excerpt:
            "A luminous tale of living constellations, fragile magic, and the courage it takes to rewrite the sky's forgotten stories.",
        date: "2025-11-04",
        displayDate: "November 04, 2025",
        image: "/images/readings/the-starglass-constellation.png",
        medium: "reading",
        categories: ["leadership"],
        tags: [],
    },
    {
        slug: "salt-in-the-shape-of-wings",
        title: "Salt in the Shape of Wings",
        author: "Mirella Arden",
        excerpt:
            "A lyrical ocean-bound meditation on belonging, memory, and the quiet courage of returning to oneself\u2014told with drifting, tidal grace.",
        date: "2025-10-07",
        displayDate: "October 07, 2025",
        image: "/images/readings/salt-in-the-shape-of-wings.png",
        medium: "reading",
        categories: ["faith"],
        tags: [],
    },

    // ── Projects ──────────────────────────────────────────────
    {
        slug: "fleet-analytics-dashboard",
        title: "Fleet Analytics Dashboard",
        excerpt:
            "Real-time telemetry and fleet management dashboard for monitoring drone operations across multiple sites.",
        date: "2025-11-15",
        displayDate: "November 15, 2025",
        image: "/images/projects/fleet-analytics-dashboard.png",
        medium: "project",
        organization: "Drone Company",
        technologies: ["React", "TypeScript", "D3.js"],
        status: "in-progress",
        categories: ["frontend"],
        tags: ["react", "typescript"],
    },
    {
        slug: "church-event-system",
        title: "Church Event System",
        excerpt:
            "Event coordination platform for managing services, volunteer schedules, and community outreach programs.",
        date: "2025-10-28",
        displayDate: "October 28, 2025",
        image: "/images/projects/church-event-system.png",
        medium: "project",
        organization: "St. Paul's Tentmakers",
        technologies: ["Astro", "Node.js", "SQLite"],
        status: "complete",
        categories: ["faith", "backend"],
        tags: ["nodejs", "community"],
    },
    {
        slug: "ecommerce-api",
        title: "E-commerce API",
        excerpt:
            "Headless commerce API powering multiple storefronts with inventory management and payment processing.",
        date: "2025-10-10",
        displayDate: "October 10, 2025",
        image: "/images/projects/ecommerce-api.png",
        medium: "project",
        organization: "Dev Shop",
        technologies: ["Go", "PostgreSQL", "Redis"],
        status: "complete",
        categories: ["backend"],
        tags: ["go", "postgresql", "redis"],
    },
    {
        slug: "garden-irrigation-controller",
        title: "Garden Irrigation Controller",
        excerpt:
            "Raspberry Pi-based irrigation system with soil moisture sensors, weather API integration, and a mobile dashboard.",
        date: "2025-09-15",
        displayDate: "September 15, 2025",
        image: "/images/projects/garden-irrigation.png",
        medium: "project",
        organization: "Personal",
        technologies: ["Rust", "MQTT", "React Native"],
        status: "in-progress",
        categories: ["homesteading"],
        tags: ["rust", "gardening"],
    },
    {
        slug: "community-tool-library",
        title: "Community Tool Library",
        excerpt:
            "Inventory and lending system for a neighborhood tool-sharing cooperative, with check-in/check-out tracking.",
        date: "2025-08-20",
        displayDate: "August 20, 2025",
        image: "/images/projects/community-tool-library.png",
        medium: "project",
        organization: "Idea Bucket",
        technologies: ["Astro", "SQLite", "Tailwind"],
        status: "archived",
        categories: ["homesteading", "frontend"],
        tags: ["community"],
    },
]
